name: Deploy Application

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-container:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-container:latest

      - name: Run Docker Container with API Keys
        run: |
          # Stop and remove any existing container with the same name (optional)
          docker stop my-app-container || true
          docker rm my-app-container || true
          # Run the container with environment variables for your API keys
          docker run -d \
            --name my-app-container \
            -e MISTRAL_API_KEY="${{ secrets.MISTRAL_API_KEY }}" \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e ANOTHER_API_KEY="${{ secrets.ANOTHER_API_KEY }}" \
            ${{ secrets.DOCKER_USERNAME }}/my-container:latest
